### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by dmytro-katrevych** [dmytro-katrevych/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by katrevichdv** [comment]
<section>
    <h3>LIFE & EDUCATION</h3>
    <p class="tags small">To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.</p>
</section>

<section>
    <h3>Languages</h3>
    <p class="tags small">
        <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span>
        <a href="/ch" hreflang="" rel="alternate" class="language" lang="ch">&#x1f1f8;&#x1f1f3;
            <span>MANDARIN</span></a>
        <a href="/jp" hreflang="" rel="alternate" class="language" lang="jp">&#x1f1ef;&#x1f1f5;
            <span>JAPANESE</span></a>
    </p>
</section>

<section>
    <h3>PUBLICATIONS</h3>
    <p>The true and humble story of me under pseudonim Tyler Wilde in an article "The evolution of Ken and Ryu"<sup><em>2011</em></sup></p>
    <p>For 15 years I have published comic books with Udon Entertainment depicting my adventures, bitter lessons and great victories.<sup><em>2003-2018</em></sup></p>
</section>

<hr>
<section>
    <h3>ACHIEVEMENTS</h3>
    <ul>
        <li>#1 in "Top 25 Street Fighter Characters" by IGN, who also called me "fancy", "icon" and "a testament to the virtue of simplicity" ❤️</li>
        <li>#2 in "Top 20 Street Fighter Characters of All Time" by GameDaily, same council found me worth of #6 place in "Top 25 Capcom Characters of All Time", which I proudly share with my partner Ken</li>
        <li>I was named "5th Most Powerful Street Fighter Character" by Screen Rant-san</li>
        <li>#71 in "Top 100 Heroes of All Time" by UGO Networks, also recognized #2 in their list of "Top 50 Street Fighter Characters"</li>
        <li>In a survey of 4000 online matches for Super Street Fighter IV, I got to be the most popular character, with 16.6% of players choosing my side</li>
      </ul>
</section>
<hr>

<section>
    <h3>SKILLS</h3>
    <p class="tags small">KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS</p>
</section>

<section>
    <h3>CHARACTER</h3>
    <p class="tags small">NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE</p>
</section>

<section>
    <h3>LIFE LESSON</h3>
    <p class="tags small">You must defeat Sheng Long to stand a chance.</p>
</section>

<section>
    <h3>Likes&#x1f603;</h3>
    <p class="tags small">GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY</p>
</section>

<section>
    <h3>Dislikes&#x1f61e;</h3>
    <p class="tags small">BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES</p>
</section>

<section>
    <h3>Wants&#x1f97a;</h3>
    <p class="tags small bulleted"><span class="tag">BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</p>
  </section>
